spring:
  datasource: 
    username: root
    password: Akshu12345
    url: jdbc:mysql://localhost:3306/great_outdoors
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# data jpa spec

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
com:
  cogent:
    GreatOutdoors:
      jwtSecret: 3000
      jwtExpirationMs: 86400000

